## Preparing the Dataset

In [289]:
# checking venv

import sys
print(sys.executable)

/home/gusbeihel@GU.GU.SE/ml2-final-project/.venv/bin/python

In [290]:
import json
import pandas as pd
import numpy as np

In [291]:
# loading the original data (not clean JSONL)

def load_json_objects(filepath):
    with open(filepath, encoding="utf-8") as f:
        content = f.read()

    decoder = json.JSONDecoder()
    records = []
    position = 0

    while position < len(content):
        # Skip whitespace between objects
        while position < len(content) and content[position].isspace():
            position += 1

        if position >= len(content):
            break

        obj, position = decoder.raw_decode(content, position)
        records.append(obj)

    return pd.DataFrame(records)

train_split = load_json_objects("../data/train.jsonl")
dev_split = load_json_objects("../data/dev.jsonl")
test_split = load_json_objects("../data/test.jsonl")

print("Train:", train_split.shape)
print("Dev:", dev_split.shape)
print("Test:", test_split.shape)

display(train_split.head())

Train: (384, 11)
Dev: (103, 11)
Test: (484, 11)

,author,question_ending,question,preceding_turns,paragraph,paragraph_with_author_and_marker,full_turn,full_turn_with_marker,following_turns,subreddit,label
0,Person_B,why not,"Are we entitled, for example, to require that ...",Person_A: Alexander Hamilton once stressed the...,"Furthermore, if we are allowed to have additio...","Person_B: Furthermore, if we are allowed to ha...","Person_B: Sure, but what is that basis? Why th...","Person_B: Sure, but what is that basis? Why th...","Person_C: > &gt; Are we entitled, for example,...",changemyview,informational
1,Person_B,why,Why?,Person_A: Pretty much what it says in the titl...,&gt;and taxes are the natural cost of having a...,Person_B: &gt;and taxes are the natural cost o...,Person_B: &gt;I enjoy paying my taxes\n\nCan't...,Person_B: &gt;I enjoy paying my taxes\n\nCan't...,"Person_C: > &gt; Yes, but you're assuming gove...",changemyview,informational
2,Person_C,how,How?,Person_A: And how many people answered?\nPerso...,How? It is a matter of probability. Suppose a ...,Person_C: <ques>How?</ques> It is a matter of ...,"Person_C: If a country has a million people, a...","Person_C: If a country has a million people, a...",Person_A: > Of course if its based on random p...,europe,rhetorical
3,Person_B,how,And that changes things how?,"Person_A: The 2% obligation is not in place, y...",Person_B: And that changes things how? The US ...,Person_B: <ques>And that changes things how?</...,Person_B: And that changes things how? The US ...,Person_B: <ques>And that changes things how?</...,Person_C: > Let's take the world's most overbl...,europe,rhetorical
4,Person_B,why,Why?,Person_A: There is no conflict with the exampl...,Person_B: &gt;It's certainly possible. It's j...,Person_B: &gt;It's certainly possible. It's j...,Person_B: &gt;It's certainly possible. It's j...,Person_B: &gt;It's certainly possible. It's j...,Person_A: > Because where do you draw the line...,changemyview,informational

In [292]:
# converting the data to proper JSONL

train_split.to_json("../data/train_clean.jsonl", orient="records", lines=True, force_ascii=False)
dev_split.to_json("../data/dev_clean.jsonl", orient="records", lines=True, force_ascii=False)
test_split.to_json("../data/test_clean.jsonl", orient="records", lines=True, force_ascii=False)

train_split = pd.read_json("../data/train_clean.jsonl", lines=True)
dev_split = pd.read_json("../data/dev_clean.jsonl", lines=True)
test_split = pd.read_json("../data/test_clean.jsonl", lines=True)

I will use the preceding turn as my context condition for each question.

In [293]:
# empty preceding turns
print(train_split["preceding_turns"].isna().sum())

# preceding turns with empty string
print(train_split["preceding_turns"].str.strip().eq("").sum())

# non-textual content in preceding turns
print(train_split["preceding_turns"].str.contains(
    "<non-textual content>", regex=False
).sum())

# ... only non-textual content
print(train_split["preceding_turns"].str.fullmatch(
    r"\s*Person_(?:\w+|\[deleted\]):\s*<non-textual content>\s*"
).sum())

# checking for [removed] or [deleted]
print(train_split["preceding_turns"].str.fullmatch(
    r"\s*Person_(?:\w+|\[deleted\]):\s*(?:\[removed\]|\[deleted\])\s*"
).sum())

# checking for only non-textual or deleted content
print(train_split["preceding_turns"].str.fullmatch(
    r"(?:\s*Person_(?:\w+|\[deleted\]):\s*(?:<non-textual content>|\[removed\]|\[deleted\]))+\s*"
).sum())

0
21
48
18
0
18

In [294]:
# empty preceding turns
print(dev_split["preceding_turns"].isna().sum())

# preceding turns with empty string
print(dev_split["preceding_turns"].str.strip().eq("").sum())

# non-textual content in preceding turns
print(dev_split["preceding_turns"].str.contains(
    "<non-textual content>", regex=False
).sum())

# ... only non-textual content
print(dev_split["preceding_turns"].str.fullmatch(
    r"\s*Person_(?:\w+|\[deleted\]):\s*<non-textual content>\s*"
).sum())

# checking for [removed] or [deleted]
print(dev_split["preceding_turns"].str.fullmatch(
    r"\s*Person_(?:\w+|\[deleted\]):\s*(?:\[removed\]|\[deleted\])\s*"
).sum())

# checking for only non-textual or deleted content
print(dev_split["preceding_turns"].str.fullmatch(
    r"(?:\s*Person_(?:\w+|\[deleted\]):\s*(?:<non-textual content>|\[removed\]|\[deleted\]))+\s*"
).sum())

0
10
8
3
0
3

In [295]:
# empty preceding turns
print(test_split["preceding_turns"].isna().sum())

# preceding turns with empty string
print(test_split["preceding_turns"].str.strip().eq("").sum())

# non-textual content in preceding turns
print(test_split["preceding_turns"].str.contains(
    "<non-textual content>", regex=False
).sum())

# ... only non-textual content
print(test_split["preceding_turns"].str.fullmatch(
    r"\s*Person_(?:\w+|\[deleted\]):\s*<non-textual content>\s*"
).sum())

# checking for [removed] or [deleted]
print(test_split["preceding_turns"].str.fullmatch(
    r"\s*Person_(?:\w+|\[deleted\]):\s*(?:\[removed\]|\[deleted\])\s*"
).sum())

# checking for only non-textual or deleted content
print(test_split["preceding_turns"].str.fullmatch(
    r"(?:\s*Person_(?:\w+|\[deleted\]):\s*(?:<non-textual content>|\[removed\]|\[deleted\]))+\s*"
).sum())

0
27
51
19
0
19

Based on the results above, I will filter out preceding turns that:
- are empty strings (with or without whitespaces)
- are only non-textual content (possibly with a deleted author)

In [296]:
# original label distribution

print("train:\n", train_split["label"].value_counts(normalize=True))
print("dev:\n", dev_split["label"].value_counts(normalize=True))
print("test:\n", test_split["label"].value_counts(normalize=True))

train:
 label
rhetorical       0.59375
informational    0.40625
Name: proportion, dtype: float64
dev:
 label
rhetorical       0.601942
informational    0.398058
Name: proportion, dtype: float64
test:
 label
rhetorical       0.659091
informational    0.340909
Name: proportion, dtype: float64

In [297]:
# filtering train

empty = train_split["preceding_turns"].str.strip().eq("")

non_textual = train_split["preceding_turns"].str.fullmatch(
    r"(?:\s*Person_(?:\w+|\[deleted\]):\s*(?:<non-textual content>|\[removed\]|\[deleted\]))+\s*"
)

train_filtered = train_split[~(empty | non_textual)].copy()

train_filtered["label"].value_counts(normalize=True)

label
rhetorical       0.611594
informational    0.388406
Name: proportion, dtype: float64

In [298]:
# filtering dev

empty = dev_split["preceding_turns"].str.strip().eq("")

non_textual = dev_split["preceding_turns"].str.fullmatch(
    r"(?:\s*Person_(?:\w+|\[deleted\]):\s*(?:<non-textual content>|\[removed\]|\[deleted\]))+\s*"
)

dev_filtered = dev_split[~(empty | non_textual)].copy()

dev_filtered["label"].value_counts(normalize=True)

label
rhetorical       0.644444
informational    0.355556
Name: proportion, dtype: float64

In [299]:
# filtering test

empty = test_split["preceding_turns"].str.strip().eq("")

non_textual = test_split["preceding_turns"].str.fullmatch(
    r"(?:\s*Person_(?:\w+|\[deleted\]):\s*(?:<non-textual content>|\[removed\]|\[deleted\]))+\s*"
)

test_filtered = test_split[~(empty | non_textual)].copy()

test_filtered["label"].value_counts(normalize=True)

label
rhetorical       0.680365
informational    0.319635
Name: proportion, dtype: float64

In [300]:
# counting how many examples were removed

print("train:\n", len(train_split))
print(len(train_filtered))

print("dev:\n", len(dev_split))
print(len(dev_filtered))

print("test:\n", len(test_split))
print(len(test_filtered))

train:
 384
345
dev:
 103
90
test:
 484
438

In total, filtering removed 98 examples.  
Filtering removed more informational questions than rhetorical questions.

### Preparing to match context lenghts

In [301]:
# inspecting context lengths (by word counts)

train_filtered["context_length"] = (
    train_filtered["preceding_turns"].str.split().str.len()
)

print("train:\n", train_filtered["context_length"].describe())

dev_filtered["context_length"] = (
    dev_filtered["preceding_turns"].str.split().str.len()
)

print("dev:\n", dev_filtered["context_length"].describe())

test_filtered["context_length"] = (
    test_filtered["preceding_turns"].str.split().str.len()
)

print("test:\n", test_filtered["context_length"].describe())

train:
 count     345.000000
mean      366.110145
std       434.572076
min         4.000000
25%       121.000000
50%       228.000000
75%       459.000000
max      3361.000000
Name: context_length, dtype: float64
dev:
 count      90.000000
mean      342.411111
std       296.504956
min        11.000000
25%       117.250000
50%       250.500000
75%       468.000000
max      1606.000000
Name: context_length, dtype: float64
test:
 count     438.000000
mean      362.906393
std       467.079742
min         6.000000
25%       104.250000
50%       225.500000
75%       440.000000
max      4423.000000
Name: context_length, dtype: float64

Context length varies. Comparing mean and median, there seems to be a small number of longer context lengths dragging up the mean. Therefore, I will try to roughly length-match the contexts when creating the swapped condition.  

I will use quartiles to ensure roughly equal sized groups:  
shortest 25%  
next 25%  
next 25%  
longest 25%

### Swapping the dev and test sets

In [302]:
# quartiles for dev

dev_filtered["length_group"] = pd.qcut(
    dev_filtered["context_length"],
    q=4,
    labels=False
)

dev_filtered["length_group"].value_counts()

length_group
0    23
3    23
2    22
1    22
Name: count, dtype: int64

In [303]:
# swapping group 0

group = dev_filtered[dev_filtered["length_group"] == 0]
indices = group.index.to_numpy()
#print(group)
print(indices)

# random shuffling indices with seed
rng = np.random.default_rng(42)
shuffled_indices = rng.permutation(indices)
print(shuffled_indices)

# rolling (shifting) indices one spot -> no self-swaps later
rolled_indices = np.roll(shuffled_indices, 1)
print(rolled_indices)

# swapping contexts
dev_filtered["swapped_context"] = None # new column
#dev_filtered.loc[shuffled_indices, "swapped_context"]
#dev_filtered.loc[rolled_indices, "preceding_turns"] # source contexts

dev_filtered.loc[shuffled_indices, "swapped_context"] = dev_filtered.loc[rolled_indices, "preceding_turns"].to_numpy()

[ 3  4  8 12 25 31 33 35 50 53 58 60 61 63 65 68 71 74 76 78 89 94 98]
[76 58 74 98 71 68 35 33 53 12  3 78 61 31 60 65 94  8 25 89  4 63 50]
[50 76 58 74 98 71 68 35 33 53 12  3 78 61 31 60 65 94  8 25 89  4 63]

In [304]:
# verifying

dev_filtered.loc[
    shuffled_indices[:3],
    ["question", "preceding_turns", "swapped_context"]
]

,question,preceding_turns,swapped_context
76,How so?,Person_A: <non-textual content>\nPerson_B: Eur...,Person_A: Yes but if you're not making profit....
58,Again how so?,Person_A: Not true.\nPerson_B: How so? Google ...,Person_A: <non-textual content>\nPerson_B: Eur...
74,"You can sue, but sue for what?",Person_A: I was sexually assaulted last year a...,Person_A: Not true.\nPerson_B: How so? Google ...

In [305]:
def swap_group(group_num: int, filtered_split, rng):

    # getting the indices
    group = filtered_split[filtered_split["length_group"] == group_num]
    indices = group.index.to_numpy()
    print("indices:", indices)

    # random shuffling indices with seed
    shuffled_indices = rng.permutation(indices)
    print("shuffled indices:", shuffled_indices)

    # rolling indices one spot -> no self-swaps later
    rolled_indices = np.roll(shuffled_indices, 1)
    print("rolled indices:", rolled_indices)

    # swapping contexts in new column
    filtered_split.loc[shuffled_indices, "swapped_context"] = filtered_split.loc[rolled_indices, "preceding_turns"].to_numpy()

    return filtered_split

In [306]:
# swapping within each of the four groups for the dev set

# creating random generator with seed
rng = np.random.default_rng(42)

# initializing the new swapped context column
dev_filtered["swapped_context"] = None

for group_num in range(4):
    dev_filtered = swap_group(group_num, dev_filtered, rng)

indices: [ 3  4  8 12 25 31 33 35 50 53 58 60 61 63 65 68 71 74 76 78 89 94 98]
shuffled indices: [76 58 74 98 71 68 35 33 53 12  3 78 61 31 60 65 94  8 25 89  4 63 50]
rolled indices: [50 76 58 74 98 71 68 35 33 53 12  3 78 61 31 60 65 94  8 25 89  4 63]
indices: [  6  11  19  23  37  40  44  47  48  52  59  70  73  80  81  82  83  85
  86  92 100 101]
shuffled indices: [ 52 101  44  86  11  37  48  70  47  81  40 100  73   6  83  82  92  19
  59  23  80  85]
rolled indices: [ 85  52 101  44  86  11  37  48  70  47  81  40 100  73   6  83  82  92
  19  59  23  80]
indices: [  0   7   9  13  14  16  18  20  26  41  45  51  64  69  72  77  79  84
  93  96  97 102]
shuffled indices: [ 97  93  77  84  20  64  14  69  26  18  45   0  16   7  79  41   9  13
 102  72  96  51]
rolled indices: [ 51  97  93  77  84  20  64  14  69  26  18  45   0  16   7  79  41   9
  13 102  72  96]
indices: [10 15 17 21 22 24 27 28 29 34 36 39 42 43 46 54 66 75 87 88 91 95 99]
shuffled indices: [27 75 17 29 43 22 39 34 66 87 46 42 95 21 54 28 24 10 88 99 91 15 36]
rolled indices: [36 27 75 17 29 43 22 39 34 66 87 46 42 95 21 54 28 24 10 88 99 91 15]

In [ ]:
# checking for missing swapped contexts
print(dev_filtered["swapped_context"].isna().sum())

# checking for identical original and swapped contexts
print((dev_filtered["preceding_turns"] == dev_filtered["swapped_context"]).sum())

# verifying
dev_filtered.loc[
    :,
    ["question", "preceding_turns", "swapped_context"]
].sample(30, random_state=42)

0
0

,question,preceding_turns,swapped_context
46,Why?,"Person_A: &gt; I dispute P3, and possibly more...","Person_A: By definition, if half the country b..."
25,How?,Person_A: I feel like you're going to have to ...,Person_[deleted]: At different times of my lif...
66,Furthermore what?,Person_A: Hello. Just looking for some advice....,"Person_A: &gt; Poor phrasing, in retrospect. T..."
82,Why not?,Person_A: Let me ask you a question: Do you th...,Person_A: Are you being serious?\nPerson_B: .....
0,Why?,Person_A: I'm in the process of buying a condo...,Person_A: You've made an enormous assumption t...
29,And why?,Person_A: &gt;We are the West\n\nThis is exact...,Person_[deleted]: [Here][URL]'s a paper that w...
45,"If not, why not?",Person_A: You've made an enormous assumption t...,Person_A: 34 states in the US have enacted Vot...
77,Why?,Person_A: My neighbor set a live trap in his y...,Person_A: I have heard a lot of modern parents...
13,What?,Person_A: &gt; You CANNOT be an environmentali...,Person_A: &gt; He is a very well respected rep...
51,Were they right to do so?,Person_A: Because Hitler invaded fucking Polan...,Person_A: Do you think your dad is doing this ...
94,Why not?,Person_A: [removed]\nPerson_B: &gt;If a human ...,Person_A: Don't understand this popcorn thing....
41,Why/why not?,Person_A: Software still has costs associated ...,Person_A: I think he means the front-line sold...
68,How?,Person_A: I only gained admission because of t...,Person_A: It would be hard to complain about s...
99,"Another point, would the news majority of US m...",Person_A: I see a lot of people talk about the...,"Person_A: So, for whatever reason, most Youtub..."
15,"Even in the 21st century, with all the securit...","Person_A: Apologies for not citing the source,...","Person_A: &gt;If you cause a car accident, and..."
7,"But my children will not be like that, do you ...",Person_A: I think that inheritance tax should ...,"Person_A: I live in the UK, where measurements..."
21,"Dude, what?",Person_A: A few hours ago I came across possib...,Person_A: &gt;referendums of this magnitude us...
33,Why?,Person_A: I once had a 500 € note that I broug...,Person_A: I don't understand your point. When ...
59,Why?,Person_A: http://www.keeptalkinggreece.com/201...,Person_A: This is were the US is the same as e...
74,"You can sue, but sue for what?",Person_A: I was sexually assaulted last year a...,Person_A: Not true.\nPerson_B: How so? Google ...
85,"Let me ask you something, though--why not?",Person_A: ISPs advertise an X number of megabi...,"Person_A: If it were not the law, yes. If it w..."
81,Why? PM isn't a directly elected position in t...,Person_[deleted]: [deleted]\nPerson_A: Broken ...,Person_A: Not surprising. I used to vote for M...
88,If Bieber (or his management or whoever) were ...,"Person_A: So, for whatever reason, most Youtub...","Person_A: The story starts with my mother, who..."
35,Why?,Person_A: I don't understand your point. When ...,Person_A: I only gained admission because of t...
39,"I'm sure it'd be a real corker, and would make...",Person_A: 1. Politics are boring.\n \n ...,Person_A: Have you ever encountered anyone in ...
14,"We'd be interested in assigning you flair, but...",Person_A: Welcome to r/askhistorians! The idea...,"Person_A: You know how it is, the man is alway..."
78,So?,Person_[deleted]: [deleted]\nPerson_A: I find ...,Person_A: [removed]\nPerson_B: Your view is es...
79,"OK, so what?",Person_A: I think he means the front-line sold...,Person_A: I think that inheritance tax should ...
36,"Even if he doesn't, if it's choice to make tha...",Person_A: I believe that everyone should selec...,"Person_A: Apologies for not citing the source,..."
87,Congress voting to repeal ACA for the 40th tim...,"Person_A: By definition, if half the country b...",Person_A: Hello. Just looking for some advice....

In [ ]:
# looking at one dev example

row = dev_filtered.loc[7]

print("QUESTION:\n", row["question"])
print("\nORIGINAL CONTEXT:\n", row["preceding_turns"])
print("\nSWAPPED CONTEXT:\n", row["swapped_context"])

QUESTION:
 But my children will not be like that, do you know why?

ORIGINAL CONTEXT:
 Person_A: I think that inheritance tax should be very high to enable society to benefit more from large fortunes hoarded by the rich few when they die.

I think that this would be a good way to redistribute wealth, without 'taking it away' from people who have rightfully earned it.

Currently, there are a few people living off "daddies fortune" who have not worked a day in their life, and will never need to. They didn't earn the money, they just happened to be born into the right family. Why should they benefit when there are so many people in poverty? The money could be used to lower other taxes for all, and create better social/welfare programs, healthcare, etc. to help people move out of poverty.

To prevent the tax from hitting the poorest families hardest, it should be graduated - for example, 0% on the first £325k, ~60% on £325k to £1m, and ~97% on anything over £1m. (Off the top of my head figures - actual amounts would vary, this is just for example).

This would mean that rich families still get to inherit some money (so there would still be incentive to save money and leave it for the kids) but the majority of it would be put back into society.
Person_B: &gt; I think that this would be a good way to redistribute wealth, without 'taking it away' from people who have rightfully earned it.

If I've worked my whole life to give my family an easy life, who are you to take away from them, what I have earned from them, just because I've died?
Person_A: When you are alive, the money is yours to do with what you like, take care of your family, treat them, whatever.

When you die, why should your money become the property of your children? You're no longer making decisions on how to spend it - and they didn't earn it, so why should then now take over the decisions?

SWAPPED CONTEXT:
 Person_A: I live in the UK, where measurements confuse me in endless ways. We measure weight of humans in stone/pounds, but food in kilograms, and big things in tonnes. We measure small distances in centimetres (or if you're an engineer, millimetres,) but measure height in feet and inches. We drive in miles, but lampposts are spaced apart in yards. We talk about height in feet and inches. At the pub, you order a pint of beer, but at the shop, you'd get a 2 litre bottle of lemonade (or a pint of milk... or a litre of milk.) And I'll be honest, I don't even understand Celsius, let alone Fahrenheit.

Basically, my life as a British national has been full of measurement confusion. I can't figure out any order to the way we use metric and imperial, and it's probably different for the older generation, too.

But I actually think both systems work fine. Imperial works great as it tends to revolve around 12, which has more factors than 10 (you can divide a foot by 3, 4 and 6 and 12, but a centimetre only by 2, 5, and 10.) And metric works great because it's intuitive, i.e. based on the number of fingers we have, and it's very easy to divide as its all factors of ten.

So, there are two points here:

1. I don't think there's any definitive advantage to imperial or metric systems of measurement.

2. We Brits need to frickin' buck up and choose a system already.

Please CMV, particularly the first one.

_____

&gt; *Hello, users of CMV! This is a footnote from your moderators. We'd just like to remind you of a couple of things. Firstly, please remember to* ***[read through our rules][URL]***. *If you see a comment that has broken one, it is more effective to report it than downvote it. Speaking of which,* ***[downvotes don't change views][URL]****! If you are thinking about submitting a CMV yourself, please have a look through our* ***[popular topics wiki][URL]*** *first. Any questions or concerns? Feel free to* ***[message us][URL]***. *Happy CMVing!*

In [309]:
# quartiles for test

test_filtered["length_group"] = pd.qcut(
    test_filtered["context_length"],
    q=4,
    labels=False
)

test_filtered["length_group"].value_counts()

length_group
0    110
3    110
2    109
1    109
Name: count, dtype: int64

In [310]:
# swapping within each of the four groups for the test set

# creating random generator with seed
rng = np.random.default_rng(42)

# initializing the new swapped context column
test_filtered["swapped_context"] = None

for group_num in range(4):
    test_filtered = swap_group(group_num, test_filtered, rng)

indices: [  1   7   8  12  13  18  20  23  27  31  33  37  43  46  49  52  55  57
  61  69  72  73  77  82  83  84  89  94  96 100 125 128 135 138 145 147
 152 155 159 164 167 171 175 179 192 206 211 220 221 223 224 225 226 235
 237 240 243 246 252 258 260 261 263 264 269 276 282 288 290 291 293 296
 301 305 312 319 321 325 330 333 340 342 343 349 355 366 371 377 378 381
 383 390 393 407 411 426 429 438 441 442 443 446 447 462 466 467 470 473
 475 481]
shuffled indices: [378  61 155 301 355   1  83 349  96 224 305 159 291   8 211 340 473 383
 481 258 296  13 366  84  73 371 138 462  94 319 333 466  23 377 225  89
 441 426 206  33 100 226 446 381  57 164 240 443 167 175 293  18 321   7
 243 407 264  12 393 447  72 429 179 343 135 261 246 290  82 467 330  52
 221 260  31 263 128 342  55 192 390 288 145 125 252 312 470 475 237 223
  20 442  37 411 171  77  69 147 269 220  43 235  49  46 282 152 438 276
 325  27]
rolled indices: [ 27 378  61 155 301 355   1  83 349  96 224 305 159 291   8 211 340 473
 383 481 258 296  13 366  84  73 371 138 462  94 319 333 466  23 377 225
  89 441 426 206  33 100 226 446 381  57 164 240 443 167 175 293  18 321
   7 243 407 264  12 393 447  72 429 179 343 135 261 246 290  82 467 330
  52 221 260  31 263 128 342  55 192 390 288 145 125 252 312 470 475 237
 223  20 442  37 411 171  77  69 147 269 220  43 235  49  46 282 152 438
 276 325]
indices: [ 11  15  16  19  21  24  29  39  40  42  47  53  62  63  78  91  97  98
 109 113 114 116 121 122 123 124 129 130 132 133 136 144 146 148 149 151
 153 157 165 168 170 177 184 186 188 197 198 201 202 208 212 213 217 229
 233 234 239 250 255 270 272 275 280 283 287 294 295 310 314 320 322 326
 328 338 339 345 347 358 364 368 373 375 380 385 392 394 397 399 402 403
 409 412 413 418 421 424 425 427 435 437 444 448 454 468 471 472 474 478
 479]
shuffled indices: [368 229 212 412 165  39 233 186 208 121 250 454 403 129 283  29 444 287
 201 418 151 114 149 198 170  15 424 123 157 153  97 347 109 124 373 345
 402  91 397 197 409 421  42 184 392 144 122 177  98  21 310 328 148 213
  19 133 136 326 425  40 472 468 427 479 322 320 130 239 471  16 146 314
 364 358 474 234 295 217 339 132  53 375  62  78 116  11  47 435 280 478
 380 448 168 385 294 272 113  63 275 188 399 413 437  24 394 270 202 255
 338]
rolled indices: [338 368 229 212 412 165  39 233 186 208 121 250 454 403 129 283  29 444
 287 201 418 151 114 149 198 170  15 424 123 157 153  97 347 109 124 373
 345 402  91 397 197 409 421  42 184 392 144 122 177  98  21 310 328 148
 213  19 133 136 326 425  40 472 468 427 479 322 320 130 239 471  16 146
 314 364 358 474 234 295 217 339 132  53 375  62  78 116  11  47 435 280
 478 380 448 168 385 294 272 113  63 275 188 399 413 437  24 394 270 202
 255]
indices: [  6  14  22  25  26  28  32  44  45  48  56  59  60  64  65  66  70  74
  79  87  99 101 105 106 107 108 111 112 118 119 127 137 139 156 158 160
 169 172 176 180 185 187 189 191 193 194 210 214 218 219 227 231 248 256
 257 259 265 289 298 299 300 303 304 307 309 311 315 316 317 327 331 332
 335 336 341 346 348 352 353 361 369 372 376 382 384 387 388 389 391 404
 414 417 420 422 423 428 434 439 445 450 452 453 456 460 461 463 465 476
 482]
shuffled indices: [434  59 461  28 111 112   6 180 404  70  87 156 463 303  65 391 316 450
 300 259 169 176 317 327 376 289 352 439  56 423 361 335 227 299  66 139
 105 231  79 348 453 158 332 265  26 189 119  32  60 194  25 210 465  99
 336 388 346 309 307  22 445 341 107 219 369 108 218 414 185 118 160 417
 248 372  44 384 311 382 482  74  48 101 452 331 172 193 456 257  14 304
 187 256  64 315 476 389 191 106 127  45 137 428 353 420 460 214 387 422
 298]
rolled indices: [298 434  59 461  28 111 112   6 180 404  70  87 156 463 303  65 391 316
 450 300 259 169 176 317 327 376 289 352 439  56 423 361 335 227 299  66
 139 105 231  79 348 453 158 332 265  26 189 119  32  60 194  25 210 465
  99 336 388 346 309 307  22 445 341 107 219 369 108 218 414 185 118 160
 417 248 372  44 384 311 382 482  74  48 101 452 331 172 193 456 257  14
 304 187 256  64 315 476 389 191 106 127  45 137 428 353 420 460 214 387
 422]
indices: [  2   3   4   5   9  17  30  35  41  50  51  54  58  67  76  81  85  86
  88  90  95 102 103 104 126 134 141 143 150 154 161 162 166 174 178 181
 183 190 195 196 199 203 204 207 209 215 216 230 236 238 241 242 247 249
 251 253 254 262 266 267 268 274 277 278 279 281 285 286 292 297 302 306
 313 318 323 324 334 337 344 354 356 359 360 362 363 365 370 374 379 386
 395 396 400 401 405 406 415 416 419 431 432 433 436 449 451 455 457 459
 464 483]
shuffled indices: [313 396 455 354 415 318 196   9 277 141 134 356 359  81 337 379 215  95
 274 242 370 431 207 249 199 209 238   3 230 262 344 432 285 286 183 457
 251 400 374 278 103 150 236 433 190 181 405  50  67 143   4   2 104 436
 266 324 483 362 253 416 363 241 174 406  41 459 216 451  30 279  17 195
 166  58   5 386 365 419  35 306 449 323 102 401 360  88 162 204 203  86
 267 126 154 395  54  76 292 302 464 254  51 334 297  90 178  85 281 247
 161 268]
rolled indices: [268 313 396 455 354 415 318 196   9 277 141 134 356 359  81 337 379 215
  95 274 242 370 431 207 249 199 209 238   3 230 262 344 432 285 286 183
 457 251 400 374 278 103 150 236 433 190 181 405  50  67 143   4   2 104
 436 266 324 483 362 253 416 363 241 174 406  41 459 216 451  30 279  17
 195 166  58   5 386 365 419  35 306 449 323 102 401 360  88 162 204 203
  86 267 126 154 395  54  76 292 302 464 254  51 334 297  90 178  85 281
 247 161]

In [311]:
# checking for missing swapped contexts
print(test_filtered["swapped_context"].isna().sum())

# checking for identical original and swapped contexts
print((test_filtered["preceding_turns"] == test_filtered["swapped_context"]).sum())

# verifying
test_filtered.loc[
    :,
    ["question", "preceding_turns", "swapped_context"]
].sample(30, random_state=42)

0
0

,question,preceding_turns,swapped_context
402,"''yea we did it, we are better than Americans....","Person_A: In all of this, the Russian govt's g...",Person_A: Are you seriously suggesting that so...
87,As for Europe doing fine for hundreds of years...,"Person_A: Yes, health and safety is the first ...",Person_A: I received a C&amp;D from a big comp...
310,E: would anyone downvoting care to explain why?,"Person_A: I'm 24 years old, my daughter is tur...","Person_A: Yeah, Spain is decentralized, but it..."
432,"""reactionary"" how?",Person_A: &gt; Subjects like philosophy and ge...,"Person_A: Funny, because we keep being told we..."
482,How?,Person_A: Is it really that lucrative for Alba...,Person_A: https://en.wikipedia.org/wiki/Ad_hom...
322,Recent history of what?,Person_A: They get much more value for a dolla...,Person_A: We're doing a better job fighting ag...
246,Why not?,Person_[deleted]: [deleted]\nPerson_A: As far ...,Person_A: yes all those things happened and ye...
91,What?,"Person_A: When I go to school, it makes me ver...","Person_A: In all of this, the Russian govt's g..."
478,How?,Person_A: Morality...good vs. evil...right vs....,Person_A: Going to try to throw in a special c...
445,"If not, why not?",Person_A: &gt; There are plenty of non-monogam...,Person_A: Lmfao dude this is the saddest thing...
323,How so?,Person_A: &gt;I think your problem is assuming...,Person_A: I currently believe that Trump suppo...
84,Why?,Person_A: <non-textual content>\nPerson_B: It'...,"Person_A: <non-textual content>\nPerson_B: ""We..."
253,What?,"Person_A: As a side point, on your assertion t...",Person_A: With the Quinnspiracy bullshit still...
436,How so?,Person_[deleted]: There are many parents out t...,"Person_A: Hello there. Excuse my bad grammar, ..."
175,What?,Person_A: &gt; In this case we're talking peop...,Person_A: <non-textual content>\nPerson_B: I'v...
85,Testosterone has been effectively used as an a...,Person_A: I'm 18 and I've been questioning my ...,"Person_A: Like I said, this is a misdirection...."
476,Why not?,"Person_A: Ok, so remember when that app that a...","Person_A: Washington state.\n\nTo be clear, th..."
215,Why not?,"Person_A: Oh, boy this is gonna be fun. I'm ab...","Person_A: Simply put, it's because religion is..."
82,What?,"Person_A: ""Most are commited by right-wing gro...",Person_A: &gt; Because you're burning more fue...
172,Why or why not?,Person_A: A child cannot consent to be born. T...,Person_A: A little bit of information...\n\nMe...
11,And this is a good thing how?,Person_A: https://en.wikipedia.org/wiki/2014_K...,Person_A: Ireland where I was born and lived u...
196,Why?,"Person_A: My apologies, I thought you were get...","Person_A: No, i grew up in Bavaria and the bav..."
32,Why not?,Person_A: [removed]\nPerson_B: I understand yo...,Person_A: Confirmed: 1 delta awarded to /u/Per...
454,What?,Person_A: <non-textual content>\nPerson_[delet...,Person_[deleted]: [deleted]\nPerson_A: It is t...
118,Is it cool for me to have a mandala tapestry i...,Person_A: I think your definition of cultural ...,"Person_A: Physical cash (coins, bills) is incr..."
150,"Regardless, the question remains the same, why...","Person_A: &gt; while that's a noble intention,...","Person_A: I am a woman, and I believe women ha..."
78,It's due to that because you say so?,Person_A: And yet it still remains very true.\...,Person_[deleted]: For not paying child support...
397,Why not?,Person_A: I sit in front of a PC for 8-12 hour...,"Person_A: When I go to school, it makes me ver..."
466,How?,Person_A: What martial art?\nPerson_B: To be f...,Person_A: &gt; companies win the second they d...
60,Why not?,Person_A: Do you have dysphoria? Do you know w...,Person_A: [removed]\nPerson_B: I understand yo...

In [ ]:
# looking at one test example

row = test_filtered.loc[7]

print("QUESTION:\n", row["question"])
print("\nORIGINAL CONTEXT:\n", row["preceding_turns"])
print("\nSWAPPED CONTEXT:\n", row["swapped_context"])

QUESTION:
 Why or why not?

ORIGINAL CONTEXT:
 Person_A: They still have interests. You can deny it all you want, but they still have interests.
Person_B: Okay if you want then I'll change my definition. Speciesism is the view that the pain and pleasure of your own species matters more than the equal pain and pleasure of another. Do you think this is justifiable? And if not, on what basis is it acceptable to kill non-human animals?
Person_A: Even with your moving-the-goalposts definition, it still applies to plants.

You're still killing plants. And there are plenty of ways to kill animals that are painless, so that point is fairly moot.

SWAPPED CONTEXT:
 Person_A: to be fair, with the European treaties, we gave up control of our borders and we certainly could get it back but there is no political will to do it (gotta solve this on a European level yadda yadda)
Person_[deleted]: you gave up? in all of this madness, everybody else seems the ones who gave up, having you dictating what to do, making threats and demands.

Dont put the blame on the EU. This one is on you alone.
Person_A: that is an interesting view I cannot quite share ;-)

In [313]:
# saving the filtered and swapped data

train_filtered.to_json("../data/train_processed.jsonl", orient="records", lines=True)
dev_filtered.to_json("../data/dev_processed.jsonl", orient="records", lines=True)
test_filtered.to_json("../data/test_processed.jsonl", orient="records", lines=True)